# Generated by Django 4.1.2 on 2022-10-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0006_update_transcription_annotations_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuser",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
    ]
