# Generated by Django 4.0.3 on 2022-03-25 17:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_arkindexinstance_image_element"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("transcription", "Transcription"),
                            ("classification", "Classification"),
                            ("entity", "Entity"),
                            ("elements", "Elements"),
                        ],
                        max_length=32,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="created",
                        max_length=32,
                        verbose_name="State",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("configuration", models.JSONField(blank=True, default=dict, verbose_name="Configuration")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
        ),
    ]
