# Generated by Django 4.0.3 on 2022-03-25 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_campaign"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arkindexinstance",
            options={"verbose_name": "Arkindex instance", "verbose_name_plural": "Arkindex instances"},
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={"verbose_name": "Campaign", "verbose_name_plural": "Campaigns"},
        ),
        migrations.AlterModelOptions(
            name="element",
            options={"verbose_name": "Element", "verbose_name_plural": "Elements"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Image", "verbose_name_plural": "Images"},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"verbose_name": "Membership", "verbose_name_plural": "Memberships"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
    ]
