# Generated by Django 4.0.3 on 2022-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_arkindexinstance_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="mode",
            field=models.CharField(
                choices=[
                    ("transcription", "Transcription"),
                    ("classification", "Classification"),
                    ("entity", "Entity"),
                    ("entity form", "Entity form"),
                    ("elements", "Elements"),
                ],
                max_length=32,
                verbose_name="Mode",
            ),
        ),
    ]
