# Generated by Django 4.0.4 on 2022-08-03 13:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_alter_class_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                (
                    "arkindex_slug",
                    models.CharField(blank=True, max_length=250, null=True, verbose_name="Arkindex slug"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "arkindex_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="types",
                        to="projects.arkindexinstance",
                        verbose_name="Arkindex instance",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type",
                "verbose_name_plural": "Types",
            },
        ),
        migrations.AddConstraint(
            model_name="type",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("arkindex_instance__isnull", True), ("arkindex_slug__isnull", True)),
                    models.Q(("arkindex_instance__isnull", False), ("arkindex_slug__isnull", False)),
                    _connector="OR",
                ),
                name="arkindex_fields_type_all_set_or_none_set",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="type",
            unique_together={("project", "arkindex_instance", "arkindex_slug"), ("name", "project")},
        ),
    ]
