# Generated by Django 4.1 on 2022-09-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0015_element_text_orientation"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="nb_tasks_auto_assignment",
            field=models.PositiveIntegerField(default=50, verbose_name="Number of tasks to assign per volunteer"),
        ),
    ]
