# Generated by Django 4.1.3 on 2022-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0021_project_provider_extra_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="csv_export",
            field=models.FileField(null=True, upload_to="csv_exports/"),
        ),
    ]
