# Generated by Django 4.1.6 on 2023-02-06 08:36
from urllib.parse import urljoin

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.urls import reverse

CHUNK_SIZE = 5000
BATCH_SIZE = 1000


def update_campaign_configuration(campaign, known_types):
    context_type = campaign.configuration.get("context_type")
    if context_type:
        campaign.configuration["context_type"] = known_types.get(context_type, "")

    carousel_type = campaign.configuration.get("carousel_type")
    if carousel_type:
        campaign.configuration["carousel_type"] = known_types.get(carousel_type, "")

    children_types = campaign.configuration.get("children_types")
    if children_types:
        campaign.configuration["children_types"] = [
            known_types[children_type] for children_type in children_types if known_types.get(children_type)
        ]

    campaign.save()


def link_type_to_element(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Element = apps.get_model("projects", "Element")
    Type = apps.get_model("projects", "Type")

    updated_elements = []
    for project in Project.objects.all():
        known_types = {}
        for element in project.elements.iterator(chunk_size=CHUNK_SIZE):
            if not known_types.get(element.type):
                try:
                    type = project.types.get(
                        provider=project.provider,
                        provider_object_id=element.type,
                    )
                except Type.DoesNotExist:
                    configure_url = urljoin(
                        settings.INSTANCE_URL, reverse("admin:projects_project_change", args=[project.id])
                    )
                    raise Exception(
                        f'\nThe project "{project.name}" is missing the type "{element.type}", you should fill in its provider fields (provider, provider_object_id) and hit the "Save" button at this link: {configure_url}'
                    )

                known_types[element.type] = str(type.id)

            element.new_type_id = known_types[element.type]
            updated_elements.append(element)

            # Once we have 1000 elements to update, we do it and clear the list
            if len(updated_elements) >= BATCH_SIZE:
                Element.objects.bulk_update(updated_elements, fields=["new_type"])
                updated_elements = []

        # Store instance IDs in the configurations
        for campaign in project.campaigns.all():
            update_campaign_configuration(campaign, known_types)

    # We don't forget to update the remaining elements
    if updated_elements:
        Element.objects.bulk_update(updated_elements, fields=["new_type"])


def reset_type_string(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Element = apps.get_model("projects", "Element")

    updated_elements = []
    for project in Project.objects.all():
        known_types = {}
        for element in project.elements.select_related("new_type").iterator(chunk_size=CHUNK_SIZE):
            known_types[str(element.new_type.id)] = (
                element.new_type.provider_object_id or element.new_type.name.lower().replace(" ", "_")
            )
            element.type = known_types[str(element.new_type.id)]
            updated_elements.append(element)

            # Once we have 1000 elements to update, we do it and clear the list
            if len(updated_elements) >= BATCH_SIZE:
                Element.objects.bulk_update(updated_elements, fields=["type"])
                updated_elements = []

        # Reset slug references in the configurations
        for campaign in project.campaigns.all():
            update_campaign_configuration(campaign, known_types)

    # We don't forget to update the remaining elements
    if updated_elements:
        Element.objects.bulk_update(updated_elements, fields=["type"])


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0025_campaign_max_user_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="new_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="elements",
                to="projects.type",
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(
            link_type_to_element,
            reverse_code=reset_type_string,
        ),
    ]
