# Generated by Django 4.1.6 on 2023-02-14 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0027_element_remove_old_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="element",
            options={"ordering": ("order",), "verbose_name": "Element", "verbose_name_plural": "Elements"},
        ),
    ]
