# Generated by Django 4.1.7 on 2023-04-05 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0032_alter_project_illustration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="type",
            options={"ordering": ("name",), "verbose_name": "Type", "verbose_name_plural": "Types"},
        ),
    ]
