# Generated by Django 4.2.7 on 2023-12-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0040_new_arkindex_wv_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="elements",
                to="projects.type",
                verbose_name="Type",
            ),
        ),
    ]
