# Generated by Django 5.0.3 on 2024-04-08 07:55

from django.db import migrations, models

import callico.projects.models

CHUNK_SIZE = 5000
BATCH_SIZE = 1000


def migrate_existing_transcriptions(apps, schema_editor):
    Element = apps.get_model("projects", "Element")

    updated = []
    for element in Element.objects.all().iterator(chunk_size=CHUNK_SIZE):
        if not element.provider_transcription_id:
            continue

        element.transcription = {"id": element.provider_transcription_id, "text": element.transcription_text}
        updated.append(element)

        # Once we have BATCH_SIZE elements to update, we do it and clear the list
        if len(updated) >= BATCH_SIZE:
            Element.objects.bulk_update(updated, fields=["transcription"])
            updated = []

    # We don't forget to update the remaining elements
    if updated:
        Element.objects.bulk_update(updated, fields=["transcription"])


def reset_transcriptions(apps, schema_editor):
    Element = apps.get_model("projects", "Element")

    updated = []
    for element in Element.objects.all().iterator(chunk_size=CHUNK_SIZE):
        if not element.transcription:
            continue

        element.provider_transcription_id = element.transcription["id"]
        element.transcription_text = element.transcription["text"]
        updated.append(element)

        # Once we have BATCH_SIZE elements to update, we do it and clear the list
        if len(updated) >= BATCH_SIZE:
            Element.objects.bulk_update(updated, fields=["provider_transcription_id", "transcription_text"])
            updated = []

    # We don't forget to update the remaining elements
    if updated:
        Element.objects.bulk_update(updated, fields=["provider_transcription_id", "transcription_text"])


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0042_fetch_arkindex_wr"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="transcription",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[callico.projects.models.simple_dict],
                verbose_name="Transcription",
            ),
        ),
        migrations.RunPython(
            migrate_existing_transcriptions,
            reverse_code=reset_transcriptions,
        ),
        migrations.RemoveConstraint(
            model_name="element",
            name="transcription_fields_all_set_or_none_set",
        ),
        migrations.RemoveField(
            model_name="element",
            name="provider_transcription_id",
        ),
        migrations.RemoveField(
            model_name="element",
            name="transcription_text",
        ),
    ]
