# Generated by Django 5.0.6 on 2024-06-06 08:44

from django.db import migrations

from callico.projects.forms import ENTITY_TRANSCRIPTION_DISPLAY_NEXT_TO_IMAGE
from callico.projects.models import CampaignMode


def update_entity_campaign_display(apps, schema_editor):
    Campaign = apps.get_model("projects", "Campaign")

    updated = []
    for campaign in Campaign.objects.filter(mode=CampaignMode.Entity):
        if campaign.configuration.get("transcription_display") != "on_image":
            continue

        # We are removing the `on_image` display mode for Entity campaigns
        campaign.configuration["transcription_display"] = ENTITY_TRANSCRIPTION_DISPLAY_NEXT_TO_IMAGE
        updated.append(campaign)

    Campaign.objects.bulk_update(updated, fields=["configuration"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0044_authority_authorityvalue"),
    ]

    operations = [
        migrations.RunPython(
            update_entity_campaign_display,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
