# Generated by Django 4.0.3 on 2022-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_arkindexinstance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arkindexinstance",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
    ]
