# Generated by Django 4.0.4 on 2022-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_campaign_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="transcription_arkindex_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Transcription Arkindex ID"),
        ),
        migrations.AddField(
            model_name="element",
            name="transcription_text",
            field=models.TextField(blank=True, null=True, verbose_name="Transcription text"),
        ),
        migrations.AddConstraint(
            model_name="element",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("transcription_arkindex_id__isnull", True), ("transcription_text__isnull", True)),
                    models.Q(("transcription_arkindex_id__isnull", False), ("transcription_text__isnull", False)),
                    _connector="OR",
                ),
                name="transcription_fields_all_set_or_none_set",
            ),
        ),
    ]
