# Generated by Django 4.0.5 on 2022-07-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_element_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="arkindex_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.arkindexinstance",
                verbose_name="Arkindex instance",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="corpus_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="Corpus ID"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("arkindex_instance__isnull", True), ("corpus_id__isnull", True)),
                    models.Q(("arkindex_instance__isnull", False), ("corpus_id__isnull", False)),
                    _connector="OR",
                ),
                name="arkindex_fields_all_set_or_none_set",
            ),
        ),
    ]
