# Generated by Django 4.0.5 on 2022-07-07 11:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_project_arkindex_instance_project_corpus_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("arkindex_id", models.UUIDField(blank=True, null=True, verbose_name="Arkindex ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "arkindex_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes",
                        to="projects.arkindexinstance",
                        verbose_name="Arkindex instance",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("arkindex_id__isnull", True), ("arkindex_instance__isnull", True)),
                    models.Q(("arkindex_id__isnull", False), ("arkindex_instance__isnull", False)),
                    _connector="OR",
                ),
                name="arkindex_fields_class_all_set_or_none_set",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("name", "project")},
        ),
    ]
