# Generated by Django 4.0.5 on 2022-07-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_class_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="element",
            unique_together={("arkindex_instance", "arkindex_id")},
        ),
        migrations.AddConstraint(
            model_name="element",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("order", "parent"),
                name="element_unique_order_in_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="element",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("order", "project"),
                name="element_unique_order_in_project",
            ),
        ),
    ]
