# Generated by Django 4.0.4 on 2022-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0011_alter_element_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("project", "arkindex_instance", "arkindex_id"), ("name", "project")},
        ),
    ]
