# Generated by Django 4.0.4 on 2022-08-18 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0013_type_type_arkindex_fields_type_all_set_or_none_set_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="projects.element",
                verbose_name="Parent",
            ),
        ),
    ]
