# Generated by Django 4.0.4 on 2022-08-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_alter_element_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="text_orientation",
            field=models.TextField(
                choices=[("left_to_right", "Left to right"), ("right_to_left", "Right to left")],
                default="left_to_right",
                max_length=32,
                verbose_name="Text orientation",
            ),
        ),
    ]
