# Generated by Django 4.1.1 on 2022-10-21 14:10

from django.db import migrations, models

import callico.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_alter_element_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[callico.projects.models.simple_dict],
                verbose_name="Metadata",
            ),
        ),
    ]
