# Generated by Django 4.0.5 on 2022-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_rename_model_fields_and_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="mode",
            field=models.CharField(
                choices=[
                    ("transcription", "Transcription"),
                    ("classification", "Classification"),
                    ("entity", "Entity"),
                    ("entity form", "Entity form"),
                    ("element_group", "Element group"),
                    ("elements", "Elements"),
                ],
                max_length=32,
                verbose_name="Mode",
            ),
        ),
    ]
