# Generated by Django 4.1.5 on 2023-01-13 13:52

from django.db import migrations, models

from callico.process.arkindex.tasks import arkindex_fetch_extra_info
from callico.process.models import ProcessMode
from callico.projects.models import ProviderType


def set_types_folder_boolean(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Process = apps.get_model("process", "Process")

    for project in Project.objects.filter(types__isnull=False, provider__type=ProviderType.Arkindex).distinct():
        fetch_process = Process.objects.create(
            name="Retrieval of extra information from Arkindex to update stored Types following a migration",
            mode=ProcessMode.ArkindexImport,
            configuration={
                "arkindex_provider": str(project.provider.id),
                "project_id": str(project.id),
            },
            project=project,
        )
        # Will allow to update the "folder" boolean on already existing Types
        arkindex_fetch_extra_info.apply_async(kwargs=fetch_process.configuration, task_id=str(fetch_process.id))

        print(
            f'A process to update Arkindex extra information has been created and started for the project "{project.name}" (ID: {project.id}).'
        )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0022_campaign_csv_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="folder",
            field=models.BooleanField(default=False, verbose_name="Folder"),
        ),
        migrations.RunPython(
            set_types_folder_boolean,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
