# Generated by Django 4.1.7 on 2023-03-15 11:22

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0028_alter_element_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="illustration",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[300, 300],
                upload_to="project_illustrations/",
                verbose_name="Illustration",
            ),
        ),
    ]
