# Generated by Django 4.1.7 on 2023-03-27 08:53

from django.db import migrations, models

import callico.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0033_alter_type_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="entities",
            field=models.JSONField(
                blank=True, default=list, validators=[callico.projects.models.list_of_dict], verbose_name="Entities"
            ),
        ),
    ]
