# Generated by Django 4.1.7 on 2023-03-30 11:57

from django.db import migrations, models

import callico.projects.models


def populate_invite_tokens(apps, schema_editor):
    Project = apps.get_model("projects", "Project")

    for project in Project.objects.all():
        project.invite_token = callico.projects.models.generate_token()
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0034_element_entities"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="invite_token",
            field=models.SlugField(null=True, unique=True, verbose_name="Invite token"),
        ),
        migrations.RunPython(
            populate_invite_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="project",
            name="invite_token",
            field=models.SlugField(
                default=callico.projects.models.generate_token,
                unique=True,
                verbose_name="Invite token",
            ),
        ),
    ]
