# Generated by Django 4.2.5 on 2023-09-15 13:10

from functools import partial

from django.db import migrations, transaction

from callico.process.arkindex.tasks import arkindex_fetch_extra_info
from callico.process.models import ProcessMode
from callico.projects.models import ProviderType


def update_projects_worker_versions_info(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Process = apps.get_model("process", "Process")

    for project in Project.objects.filter(provider__type=ProviderType.Arkindex):
        project.provider_extra_information = {}
        project.save()

        fetch_process = Process.objects.create(
            name="Retrieval of extra information from Arkindex to update stored WorkerVersions following an Arkindex release",
            mode=ProcessMode.ArkindexImport,
            configuration={
                "arkindex_provider": str(project.provider.id),
                "project_id": str(project.id),
            },
            project=project,
        )
        # We use transaction.on_commit() to avoid a race condition preventing Celery from seeing the newly created Process
        transaction.on_commit(
            partial(
                arkindex_fetch_extra_info.apply_async, kwargs=fetch_process.configuration, task_id=str(fetch_process.id)
            )
        )

        print(
            f'A process to update Arkindex extra information has been created and started for the project "{project.name}" (ID: {project.id}).'
        )


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0039_type_color"),
    ]

    operations = [
        migrations.RunPython(
            update_projects_worker_versions_info,
            reverse_code=update_projects_worker_versions_info,
        ),
    ]
