# Generated by Django 5.0.6 on 2024-05-15 15:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0043_element_transcription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Authority",
                "verbose_name_plural": "Authorities",
            },
        ),
        migrations.CreateModel(
            name="AuthorityValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "authority_value_id",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Value identifier in authority",
                    ),
                ),
                ("value", models.TextField(verbose_name="Value")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="projects.authority",
                        verbose_name="Authority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authority value",
                "verbose_name_plural": "Authority values",
            },
        ),
    ]
