# Generated by Django 4.1.3 on 2022-11-21 09:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0019_rename_model_fields_and_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("arkindex_import", "Arkindex import"),
                            ("arkindex_export", "Arkindex export"),
                            ("csv_export", "CSV export"),
                        ],
                        max_length=32,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="created",
                        max_length=32,
                        verbose_name="State",
                    ),
                ),
                ("configuration", models.JSONField(blank=True, default=dict, verbose_name="Configuration")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("started", models.DateTimeField(blank=True, null=True, verbose_name="Started")),
                ("ended", models.DateTimeField(blank=True, null=True, verbose_name="Ended")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process",
                "verbose_name_plural": "Processes",
            },
        ),
    ]
