# Generated by Django 4.1.6 on 2023-02-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="name",
            field=models.CharField(max_length=512, verbose_name="Name"),
        ),
    ]
