# Generated by Django 4.1.7 on 2023-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0002_alter_process_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="logs",
            field=models.TextField(blank=True, default="", verbose_name="Logs"),
        ),
    ]
