# Generated by Django 4.0.3 on 2022-03-24 11:37

import uuid

import django.db.models.deletion
from django.db import migrations, models

import callico.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArkindexInstance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("api_url", models.URLField(unique=True, verbose_name="API URL")),
                ("api_token", models.CharField(max_length=100, verbose_name="API token")),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("iiif_url", models.URLField(unique=True, verbose_name="IIIF URL")),
                ("width", models.PositiveIntegerField(default=0, verbose_name="Width")),
                ("height", models.PositiveIntegerField(default=0, verbose_name="Height")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
            ],
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("type", models.CharField(max_length=250, verbose_name="Type")),
                ("polygon", callico.base.fields.PolygonField(blank=True, null=True, verbose_name="Polygon")),
                ("arkindex_id", models.UUIDField(verbose_name="Arkindex ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "arkindex_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="projects.arkindexinstance",
                        verbose_name="Arkindex instance",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elements",
                        to="projects.image",
                        verbose_name="Image",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="projects.element",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "unique_together": {("arkindex_instance", "arkindex_id")},
            },
        ),
    ]
