# Generated by Django 4.0.4 on 2022-06-24 15:53

from django.db import migrations, models
from natsort import humansorted


def set_elements_order(apps, schema_editor):
    Element = apps.get_model("projects", "Element")
    Project = apps.get_model("projects", "Project")

    updated = []
    for project in Project.objects.all():
        for parent_id in project.elements.values_list("parent_id", flat=True).distinct():
            sorted_children = humansorted(
                project.elements.filter(parent_id=parent_id), key=lambda element: element.name
            )
            for i, child in enumerate(sorted_children):
                child.order = i
                updated.append(child)
    Element.objects.bulk_update(updated, fields=["order"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_element_transcription_arkindex_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Order"),
        ),
        migrations.RunPython(
            set_elements_order,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="element",
            name="order",
            field=models.PositiveIntegerField(verbose_name="Order"),
        ),
        migrations.AlterUniqueTogether(
            name="element",
            unique_together={("arkindex_instance", "arkindex_id"), ("order", "parent")},
        ),
    ]
