# Generated by Django 4.1.2 on 2022-10-24 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_campaign_nb_tasks_auto_assignment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="element",
            unique_together={("arkindex_instance", "arkindex_id", "project")},
        ),
    ]
