# Generated by Django 4.1.2 on 2022-10-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_element_metadata"),
    ]

    operations = [
        # Rename old ArkindexInstance model to Provider, update verbose names, add new "type" field
        migrations.RenameModel(old_name="ArkindexInstance", new_name="Provider"),
        migrations.AlterModelOptions(
            name="provider",
            options={"verbose_name": "Provider", "verbose_name_plural": "Providers"},
        ),
        migrations.AddField(
            model_name="provider",
            name="type",
            field=models.CharField(
                choices=[("arkindex", "Arkindex"), ("iiif", "IIIF")],
                default="arkindex",
                max_length=32,
                verbose_name="Type",
            ),
        ),
        # Rename fields related to the provider on model Project, update verbose names, rename the constraint
        migrations.RenameField(
            model_name="project",
            old_name="arkindex_instance",
            new_name="provider",
        ),
        migrations.AlterField(
            model_name="project",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.RenameField(
            model_name="project",
            old_name="corpus_id",
            new_name="provider_object_id",
        ),
        migrations.AlterField(
            model_name="project",
            name="provider_object_id",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Object identifier in provider"),
        ),
        # We have to define this step manually, because Django has to remove and add the constraint only to rename it
        # We don't want this behavior to occur in the DB as it would reapply the constraint on all existing data, that isn't necessary
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE projects_project RENAME CONSTRAINT arkindex_fields_all_set_or_none_set TO provider_fields_all_set_or_none_set",
                    reverse_sql="ALTER TABLE projects_project RENAME CONSTRAINT provider_fields_all_set_or_none_set TO arkindex_fields_all_set_or_none_set",
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="project",
                    name="arkindex_fields_all_set_or_none_set",
                ),
                migrations.AddConstraint(
                    model_name="project",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("provider__isnull", True), ("provider_object_id__isnull", True)),
                            models.Q(("provider__isnull", False), ("provider_object_id__isnull", False)),
                            _connector="OR",
                        ),
                        name="provider_fields_all_set_or_none_set",
                    ),
                ),
            ],
        ),
        # Rename fields related to the provider on model Element, update verbose names, rename the constraint
        migrations.RenameField(
            model_name="element",
            old_name="arkindex_instance",
            new_name="provider",
        ),
        migrations.AlterField(
            model_name="element",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="projects.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.RenameField(
            model_name="element",
            old_name="arkindex_id",
            new_name="provider_object_id",
        ),
        migrations.AlterField(
            model_name="element",
            name="provider_object_id",
            field=models.CharField(max_length=512, verbose_name="Object identifier in provider"),
        ),
        migrations.RenameField(
            model_name="element",
            old_name="transcription_arkindex_id",
            new_name="provider_transcription_id",
        ),
        migrations.AlterField(
            model_name="element",
            name="provider_transcription_id",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="Transcription identifier in provider"
            ),
        ),
        # We have to define this step manually, because Django has to remove and add the constraint only to rename it
        # We don't want this behavior to occur in the DB as it would reapply the constraint on all existing data, that isn't necessary
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="element",
                    name="transcription_fields_all_set_or_none_set",
                ),
                migrations.AddConstraint(
                    model_name="element",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("provider_transcription_id__isnull", True),
                                ("transcription_text__isnull", True),
                            ),
                            models.Q(
                                ("provider_transcription_id__isnull", False),
                                ("transcription_text__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="transcription_fields_all_set_or_none_set",
                    ),
                ),
            ],
        ),
        # Rename fields related to the provider on model Class, update verbose names, rename the constraint
        migrations.RenameField(
            model_name="class",
            old_name="arkindex_instance",
            new_name="provider",
        ),
        migrations.AlterField(
            model_name="class",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="projects.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.RenameField(
            model_name="class",
            old_name="arkindex_id",
            new_name="provider_object_id",
        ),
        migrations.AlterField(
            model_name="class",
            name="provider_object_id",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Object identifier in provider"),
        ),
        # We have to define this step manually, because Django has to remove and add the constraint only to rename it
        # We don't want this behavior to occur in the DB as it would reapply the constraint on all existing data, that isn't necessary
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE projects_class RENAME CONSTRAINT arkindex_fields_class_all_set_or_none_set TO provider_fields_class_all_set_or_none_set",
                    reverse_sql="ALTER TABLE projects_class RENAME CONSTRAINT provider_fields_class_all_set_or_none_set TO arkindex_fields_class_all_set_or_none_set",
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="class",
                    name="arkindex_fields_class_all_set_or_none_set",
                ),
                migrations.AddConstraint(
                    model_name="class",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("provider__isnull", True), ("provider_object_id__isnull", True)),
                            models.Q(("provider__isnull", False), ("provider_object_id__isnull", False)),
                            _connector="OR",
                        ),
                        name="provider_fields_class_all_set_or_none_set",
                    ),
                ),
            ],
        ),
        # Rename fields related to the provider on model Type, update verbose names, rename the constraint
        migrations.RenameField(
            model_name="type",
            old_name="arkindex_instance",
            new_name="provider",
        ),
        migrations.AlterField(
            model_name="type",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="types",
                to="projects.provider",
                verbose_name="Provider",
            ),
        ),
        migrations.RenameField(
            model_name="type",
            old_name="arkindex_slug",
            new_name="provider_object_id",
        ),
        migrations.AlterField(
            model_name="type",
            name="provider_object_id",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Object identifier in provider"),
        ),
        # We have to define this step manually, because Django has to remove and add the constraint only to rename it
        # We don't want this behavior to occur in the DB as it would reapply the constraint on all existing data, that isn't necessary
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE projects_type RENAME CONSTRAINT arkindex_fields_type_all_set_or_none_set TO provider_fields_type_all_set_or_none_set",
                    reverse_sql="ALTER TABLE projects_type RENAME CONSTRAINT provider_fields_type_all_set_or_none_set TO arkindex_fields_type_all_set_or_none_set",
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="type",
                    name="arkindex_fields_type_all_set_or_none_set",
                ),
                migrations.AddConstraint(
                    model_name="type",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("provider__isnull", True), ("provider_object_id__isnull", True)),
                            models.Q(("provider__isnull", False), ("provider_object_id__isnull", False)),
                            _connector="OR",
                        ),
                        name="provider_fields_type_all_set_or_none_set",
                    ),
                ),
            ],
        ),
    ]
