# Generated by Django 4.1.3 on 2022-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0020_alter_campaign_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="provider_extra_information",
            field=models.JSONField(blank=True, default=dict, verbose_name="Extra information from the provider"),
        ),
    ]
