# Generated by Django 4.1.7 on 2023-02-23 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0024_campaign_entity_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="max_user_tasks",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Number of allowed assignments for available tasks",
            ),
        ),
    ]
