# Generated by Django 4.1.7 on 2023-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0029_project_description_project_illustration"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="extra_information",
            field=models.JSONField(blank=True, default=dict, verbose_name="Extra information"),
        ),
    ]
