# Generated by Django 4.1.7 on 2023-03-21 16:49

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0030_provider_extra_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="illustration",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[600, 600],
                upload_to="project_illustrations/",
                verbose_name="Illustration",
            ),
        ),
    ]
