# Generated by Django 4.2.1 on 2023-05-23 10:06

from django.db import migrations, models


def update_campaign_states(apps, schema_editor):
    Campaign = apps.get_model("projects", "Campaign")
    Campaign.objects.filter(state="completed").update(state="closed")


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0035_project_invite_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="created",
                max_length=32,
                verbose_name="State",
            ),
        ),
        migrations.RunPython(
            update_campaign_states,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
