# Generated by Django 4.2.1 on 2023-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0036_alter_campaign_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="xlsx_export",
            field=models.FileField(null=True, upload_to="xlsx_exports/"),
        ),
    ]
