# Generated by Django 4.2.2 on 2023-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0037_campaign_xlsx_export"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="iiif_url",
            field=models.URLField(max_length=512, unique=True, verbose_name="IIIF URL"),
        ),
    ]
