# Generated by Django 4.2.3 on 2023-07-17 16:14

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0038_alter_image_iiif_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="color",
            field=models.CharField(
                default="28b62c",
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{6}$",
                        flags=re.RegexFlag["IGNORECASE"],
                        message="Color should be a hexadecimal color code",
                    )
                ],
                verbose_name="Color",
            ),
        ),
    ]
