from django.urls import path, re_path

from callico.projects.views import (
    AdminCampaignTasksList,
    CampaignCreate,
    CampaignDetails,
    CampaignInstructions,
    CampaignJoin,
    CampaignTasksCreate,
    CampaignTasksUnassign,
    CampaignUpdate,
    CampaignUpdateState,
    ContributorCampaignTasksList,
    ElementDetails,
    EntityFormObjectCreate,
    EntityFormObjectDelete,
    EntityFormObjectUpdate,
    InviteLinkManagement,
    ProjectBrowse,
    ProjectCreate,
    ProjectDetails,
    ProjectJoin,
    ProjectList,
    ProjectMemberCreate,
    ProjectMemberDelete,
    ProjectMemberList,
    ProjectMemberUpdate,
    ProjectUpdate,
    PublishDraftTasks,
)

urlpatterns = [
    path("", ProjectList.as_view(), name="projects"),
    path("create/", ProjectCreate.as_view(), name="project-create"),
    path("join/<invite_token>/", ProjectJoin.as_view(), name="project-join"),
    path("<uuid:project_id>/details/", ProjectDetails.as_view(), name="project-details"),
    path("<uuid:pk>/edit/", ProjectUpdate.as_view(), name="project-update"),
    path("<uuid:project_id>/members/", ProjectMemberList.as_view(), name="members"),
    path("<uuid:project_id>/members/new/", ProjectMemberCreate.as_view(), name="member-create"),
    path("<uuid:project_id>/members/<int:pk>/edit/", ProjectMemberUpdate.as_view(), name="member-update"),
    path("<uuid:project_id>/members/<int:pk>/delete/", ProjectMemberDelete.as_view(), name="member-delete"),
    path("<uuid:project_id>/invite-link/", InviteLinkManagement.as_view(), name="invite-link-management"),
    # To browse top elements in a project or children of a specific element
    re_path(
        r"^(?P<project_id>[0-9a-f-]{36})(?:/element/(?P<element_id>[0-9a-f-]{36}))?/$",
        ProjectBrowse.as_view(),
        name="project-browse",
    ),
    path("element/<uuid:pk>/", ElementDetails.as_view(), name="element-details"),
    path("<uuid:project_id>/campaign/create/", CampaignCreate.as_view(), name="campaign-create"),
    path("campaign/<uuid:pk>/", CampaignDetails.as_view(), name="campaign-details"),
    path("campaign/<uuid:pk>/instructions/", CampaignInstructions.as_view(), name="campaign-instructions"),
    path("campaign/<uuid:pk>/configure/", CampaignUpdate.as_view(), name="campaign-update"),
    path(
        "campaign/<uuid:pk>/configure/entity-form/new/",
        EntityFormObjectCreate.as_view(),
        name="entity-form-object-create",
    ),
    path(
        "campaign/<uuid:pk>/configure/entity-form/<int:position>/",
        EntityFormObjectUpdate.as_view(),
        name="entity-form-object-update",
    ),
    path(
        "campaign/<uuid:pk>/configure/entity-form/<int:position>/delete/",
        EntityFormObjectDelete.as_view(),
        name="entity-form-object-delete",
    ),
    path("campaign/<uuid:pk>/update-state/", CampaignUpdateState.as_view(), name="campaign-update-state"),
    path("campaign/<uuid:pk>/new-tasks/", CampaignTasksCreate.as_view(), name="tasks-create"),
    path("campaign/<uuid:pk>/publish-tasks/", PublishDraftTasks.as_view(), name="tasks-publish"),
    path("campaign/<uuid:pk>/tasks/", AdminCampaignTasksList.as_view(), name="admin-campaign-task-list"),
    path("campaign/<uuid:pk>/my-tasks/", ContributorCampaignTasksList.as_view(), name="contributor-campaign-task-list"),
    path("campaign/<uuid:pk>/unassign-tasks/", CampaignTasksUnassign.as_view(), name="tasks-unassign"),
    path("campaign/<uuid:pk>/join/", CampaignJoin.as_view(), name="campaign-join"),
]
