# Generated by Django 4.1 on 2022-08-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0004_annotation_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuser",
            name="is_preview",
            field=models.BooleanField(default=False, verbose_name="Is preview"),
        ),
    ]
