# Generated by Django 4.1.3 on 2022-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0008_alter_taskuser_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="duration",
            field=models.DurationField(null=True, blank=True, verbose_name="Completion time"),
        ),
    ]
