# Generated by Django 4.1.7 on 2023-04-06 07:58

from django.db import migrations, models

from callico.projects.models import CampaignMode

CHUNK_SIZE = 5000
BATCH_SIZE = 1000


def set_has_uncertain_value(apps, schema_editor):
    TaskUser = apps.get_model("annotations", "TaskUser")

    updated = []
    for user_task in TaskUser.objects.filter(task__campaign__mode=CampaignMode.Transcription).iterator(
        chunk_size=CHUNK_SIZE
    ):
        last_annotation = user_task.annotations.order_by("-version").first()
        if last_annotation and any(
            transcription.get("uncertain", False)
            for transcription in last_annotation.value.get("transcription", {}).values()
        ):
            user_task.has_uncertain_value = True
            updated.append(user_task)

            # Once we have 1000 user tasks to update, we do it and clear the list
            if len(updated) >= BATCH_SIZE:
                TaskUser.objects.bulk_update(updated, fields=["has_uncertain_value"])
                updated = []

    for user_task in TaskUser.objects.filter(task__campaign__mode=CampaignMode.EntityForm).iterator(
        chunk_size=CHUNK_SIZE
    ):
        last_annotation = user_task.annotations.order_by("-version").first()
        if last_annotation and any(
            entity.get("uncertain", False) for entity in last_annotation.value.get("values", [])
        ):
            user_task.has_uncertain_value = True
            updated.append(user_task)

            # Once we have 1000 user tasks to update, we do it and clear the list
            if len(updated) >= BATCH_SIZE:
                TaskUser.objects.bulk_update(updated, fields=["has_uncertain_value"])
                updated = []

    # We don't forget to update the remaining user tasks
    if updated:
        TaskUser.objects.bulk_update(updated, fields=["has_uncertain_value"])


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0010_annotation_entity_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuser",
            name="has_uncertain_value",
            field=models.BooleanField(default=False, verbose_name="Has uncertain value"),
        ),
        migrations.RunPython(
            set_has_uncertain_value,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
