# Generated by Django 4.1.7 on 2023-04-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("annotations", "0011_taskuser_has_uncertain_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_annotations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Moderator",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[("validated", "Validated"), ("rejected", "Rejected")],
                max_length=32,
                null=True,
                verbose_name="State",
            ),
        ),
    ]
