# Generated by Django 4.2.5 on 2023-10-03 08:57

from django.db import migrations

CHUNK_SIZE = 5000
BATCH_SIZE = 1000


def port_reported_comments(apps, schema_editor):
    TaskUser = apps.get_model("annotations", "TaskUser")
    Comment = apps.get_model("users", "Comment")

    to_create = []
    for user_task in (
        TaskUser.objects.filter(comment__isnull=False).exclude(comment__exact="").iterator(chunk_size=CHUNK_SIZE)
    ):
        to_create.append(
            Comment(
                user=user_task.user,
                task=user_task.task,
                content=user_task.comment,
            )
        )

        # Once we have 1000 comments to create, we do it and clear the list
        if len(to_create) >= BATCH_SIZE:
            Comment.objects.bulk_create(to_create)
            to_create = []

    # We don't forget to create the remaining comments
    if to_create:
        Comment.objects.bulk_create(to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0012_annotation_moderator_annotation_state"),
        ("users", "0007_comment"),
    ]

    operations = [
        migrations.RunPython(
            port_reported_comments,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="taskuser",
            name="comment",
        ),
    ]
