# Generated by Django 4.1 on 2022-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_validated",
            field=models.BooleanField(default=False, verbose_name="Email validated"),
        ),
    ]
