# Generated by Django 4.1.7 on 2023-03-02 14:41

from django.db import migrations, models
from django.db.models import F


def update_is_staff(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.update(is_staff=F("is_admin"))


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_email_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is staff"),
        ),
        migrations.RunPython(
            update_is_staff,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
