# Generated by Django 4.2.1 on 2023-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("process", "0003_process_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="mode",
            field=models.CharField(
                choices=[
                    ("arkindex_import", "Arkindex import"),
                    ("arkindex_export", "Arkindex export"),
                    ("csv_export", "CSV export"),
                    ("xlsx_export", "XLSX export"),
                ],
                max_length=32,
                verbose_name="Mode",
            ),
        ),
    ]
