# Generated by Django 4.0.3 on 2022-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0002_annotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskuser",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("annotated", "Annotated"),
                    ("validated", "Validated"),
                    ("rejected", "Rejected"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=32,
                verbose_name="State",
            ),
        ),
    ]
