# Generated by Django 4.0.4 on 2022-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0003_alter_taskuser_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
    ]
