# Generated by Django 4.1.3 on 2022-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0007_taskuser_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskuser",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("annotated", "Annotated"),
                    ("validated", "Validated"),
                    ("rejected", "Rejected"),
                    ("skipped", "Skipped"),
                ],
                default="draft",
                max_length=32,
                verbose_name="State",
            ),
        ),
    ]
