# Generated by Django 4.2 on 2023-04-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "French")],
                default="en",
                verbose_name="Preferred language",
            ),
        ),
    ]
