# Generated by Django 5.0.1 on 2024-01-24 14:26

from django.db import migrations, models


def set_users_display_name(apps, schema_editor):
    User = apps.get_model("users", "User")

    updated = []
    for user in User.objects.all():
        user.display_name = user.email.split("@")[0]
        updated.append(user)

    User.objects.bulk_update(updated, fields=["display_name"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, null=True, verbose_name="Display name"),
        ),
        migrations.RunPython(
            set_users_display_name,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(verbose_name="Display name"),
        ),
    ]
